### ISSUE TITLE
Support IntelliJ Idea 2021.3.3

### ISSUE THREAD

**Issue by ovitrif** [KaustubhPatange/compose-color#3]
Not supported currently and because of that, users can't install the plugin from the:
- IntelliJ Idea 2021.3.3 settings window → Plugins.

**Comment by ovitrif** [comment]
I want to contribute but I have no idea how I go about changing the versions in `gradle.properties`..:

```
pluginVersion = 0.0.4
pluginSinceBuild = 193
pluginUntilBuild = 202.*
```

**Comment by KaustubhPatange** [comment]
@ovitrif Kindly review the changes I request on the PR.

**Comment by ovitrif** [comment]
> @ovitrif Kindly review the changes I request on the PR.

Pls ping me when you do that, at the moment I don't see any requested changes on PR #4

**Comment by KaustubhPatange** [comment]
@ovitrif Go the PR #4 I've added some comments, kindly make sure to review & edit the files as requested.

**Comment by ovitrif** [comment]
@KaustubhPatange Sorry but I don't see any comments on the PR #4:
<img width="661" alt="PR4" src="https://user-images.githubusercontent.com/4588074/162445912-0aa30b33-2ed2-4e58-b10a-429cd92eb04b.png">

**Comment by KaustubhPatange** [comment]
Yeah sorry my mistake should be visible now!

**Comment by ovitrif** [comment]
Thank you @KaustubhPatange!

**Comment by ovitrif** [comment]
@KaustubhPatange Please check the PR, I added the changes you suggested.

**Comment by KaustubhPatange** [comment]
@ovitrif Your PR is merged with the changes, soon this release will be available on Jetbrain's plugin store :)

Thank you for your contribution!
